/*
 * DataSourcePanel.java
 *
 * Created on May 5, 2010, 1:52:17 PM
 */
package at.ac.ait.speedr.importwizard.steps;

import java.awt.event.ItemEvent;
import java.io.File;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author visnei
 */
public class DataSourcePanel extends javax.swing.JPanel implements DocumentListener {

    public static final String PROP_PASTE_DATA_CHANGED = "PROP_PASTE_DATA_CHANGED";
    public static final String PROP_URL_CHANGED = "PROP_URL_CHANGED";
    public static final String PROP_DATASOURCE_CHANGED = "PROP_DATASOURCE_CHANGED";
    public static final String PROP_FILE_DATASOURCE = "PROP_FILE_DATASOURCE";
    public static final String PROP_PASTEDATA_DATASOURCE = "PROP_PASTEDATA_DATASOURCE";
    public static final String PROP_URL_DATASOURCE = "PROP_URL_DATASOURCE";
    private static File lastUsedDir;
    private static String currentDataSource;

    /** Creates new form DataSourcePanel */
    public DataSourcePanel() {
        initComponents();
        fileChooser.setSelectedFile(null);
        if (lastUsedDir != null) {
            fileChooser.setCurrentDirectory(lastUsedDir);
        }
    }

    public String getCurrentDataSource() {
        return currentDataSource;
    }

    public java.io.File getSelectedFile() {
        return fileChooser.getSelectedFile();
    }

    private void selectedFileChanged(java.beans.PropertyChangeEvent evt) {
        firePropertyChange(evt.getPropertyName(), evt.getOldValue(), evt.getNewValue());
        rb_SelectFile.setSelected(true);
        if (getSelectedFile() != null) {
            lastUsedDir = getSelectedFile().getParentFile();
        }
    }

    public void insertUpdate(DocumentEvent e) {
        changedUpdate(e);
    }

    public void removeUpdate(DocumentEvent e) {
        changedUpdate(e);
    }

    public void changedUpdate(DocumentEvent e) {
        if (dataTextArea.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PASTE_DATA_CHANGED, 0, dataTextArea.getText().trim());
            rb_PasteData.setSelected(true);
        } else {
            firePropertyChange(PROP_URL_CHANGED, 0, urlTextField.getText());
            rb_URL.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTextArea = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        urlTextField = new javax.swing.JTextField();
        rb_SelectFile = new javax.swing.JRadioButton();
        rb_PasteData = new javax.swing.JRadioButton();
        rb_URL = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(475, 447));

        jScrollPane2.setBorder(null);
        jScrollPane2.setPreferredSize(null);

        fileChooser.setControlButtonsAreShown(false);
        fileChooser.addPropertyChangeListener(javax.swing.JFileChooser.SELECTED_FILE_CHANGED_PROPERTY,new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectedFileChanged(evt);
            }
        });

        dataTextArea.setColumns(20);
        dataTextArea.setRows(4);
        dataTextArea.setHighlightCurrentLine(false);
        dataTextArea.getDocument().addDocumentListener(this);
        jScrollPane1.setViewportView(dataTextArea);

        urlTextField.getDocument().addDocumentListener(this);

        buttonGroup1.add(rb_SelectFile);
        rb_SelectFile.setFont(new java.awt.Font("Tahoma", 1, 11));
        rb_SelectFile.setText("Select File");
        rb_SelectFile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_SelectFileItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rb_PasteData);
        rb_PasteData.setFont(new java.awt.Font("Tahoma", 1, 11));
        rb_PasteData.setText("Paste Data");
        rb_PasteData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_PasteDataItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rb_URL);
        rb_URL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb_URL.setText("Enter URL");
        rb_URL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_URLItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                    .addComponent(rb_PasteData)
                    .addComponent(rb_SelectFile)
                    .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(rb_URL)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(urlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rb_SelectFile)
                .addGap(1, 1, 1)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_PasteData)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_URL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rb_SelectFileItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_rb_SelectFileItemStateChanged
        if (rb_SelectFile.isSelected()) {
            setDataSource(PROP_FILE_DATASOURCE);
        }
    }//GEN-LAST:event_rb_SelectFileItemStateChanged

    private void rb_PasteDataItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_rb_PasteDataItemStateChanged
        if (rb_PasteData.isSelected()) {
            setDataSource(PROP_PASTEDATA_DATASOURCE);
        }
    }//GEN-LAST:event_rb_PasteDataItemStateChanged

    private void rb_URLItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_rb_URLItemStateChanged
        if (rb_URL.isSelected()) {
            setDataSource(PROP_URL_DATASOURCE);
        }
    }//GEN-LAST:event_rb_URLItemStateChanged

    private void setDataSource(String datasource) {
        String oldValue = currentDataSource;
        currentDataSource = datasource;
        firePropertyChange(PROP_DATASOURCE_CHANGED, oldValue, currentDataSource);
    }

    public void setSelectedFile(java.io.File f) {
        fileChooser.setSelectedFile(f);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea dataTextArea;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb_PasteData;
    private javax.swing.JRadioButton rb_SelectFile;
    private javax.swing.JRadioButton rb_URL;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
}
